// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102154359_RenameInFriendRequests")]
    partial class RenameInFriendRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Event", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Backend.Models.Expense", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("eventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.HasIndex("eventId");

                    b.HasIndex("userId");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("Backend.Models.FriendRequest", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("fromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<DateOnly>("sentAt")
                        .HasColumnType("date")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("toUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("id");

                    b.HasIndex("fromUserId");

                    b.HasIndex("toUserId");

                    b.ToTable("friend_requests");
                });

            modelBuilder.Entity("Backend.Models.Friendship", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Friend1FK")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Friend2Fk")
                        .HasColumnType("uuid");

                    b.Property<Guid>("friend1FK")
                        .HasColumnType("uuid")
                        .HasColumnName("friend1");

                    b.Property<Guid>("friend2FK")
                        .HasColumnType("uuid")
                        .HasColumnName("friend2");

                    b.Property<DateTime>("friendsSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("friends_since");

                    b.HasKey("id");

                    b.HasIndex("friend1FK");

                    b.HasIndex("friend2FK");

                    b.ToTable("friendships");
                });

            modelBuilder.Entity("Backend.Models.SpendingGoal", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("dailyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_limit");

                    b.Property<int?>("monthlyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_limit");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("weeklyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_limit");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("spending_goals");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("firebaseUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("profilePictureUrl")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Backend.Models.UserEvents", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("eventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.HasIndex("eventId");

                    b.HasIndex("userId", "eventId")
                        .IsUnique();

                    b.ToTable("user_events");
                });

            modelBuilder.Entity("Backend.Models.UserExpenseShare", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("expenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<decimal>("shareAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("share_amount");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.HasIndex("expenseId");

                    b.HasIndex("userId");

                    b.ToTable("user_expense_share");
                });

            modelBuilder.Entity("Backend.Models.Expense", b =>
                {
                    b.HasOne("Backend.Models.Event", "expenseEvent")
                        .WithMany("expenses")
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.User", "user")
                        .WithMany("expenses")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("expenseEvent");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Backend.Models.FriendRequest", b =>
                {
                    b.HasOne("Backend.Models.User", "fromUser")
                        .WithMany("sentFriendRequests")
                        .HasForeignKey("fromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "toUser")
                        .WithMany("recievedFriendRequests")
                        .HasForeignKey("toUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fromUser");

                    b.Navigation("toUser");
                });

            modelBuilder.Entity("Backend.Models.Friendship", b =>
                {
                    b.HasOne("Backend.Models.User", "friend1")
                        .WithMany("friendships")
                        .HasForeignKey("friend1FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "friend2")
                        .WithMany()
                        .HasForeignKey("friend2FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("friend1");

                    b.Navigation("friend2");
                });

            modelBuilder.Entity("Backend.Models.SpendingGoal", b =>
                {
                    b.HasOne("Backend.Models.User", "user")
                        .WithOne("spendingGoal")
                        .HasForeignKey("Backend.Models.SpendingGoal", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Backend.Models.UserEvents", b =>
                {
                    b.HasOne("Backend.Models.Event", "userEvent")
                        .WithMany("userEvents")
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "user")
                        .WithMany("userEvents")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");

                    b.Navigation("userEvent");
                });

            modelBuilder.Entity("Backend.Models.UserExpenseShare", b =>
                {
                    b.HasOne("Backend.Models.Expense", "expense")
                        .WithMany("userExpenseShares")
                        .HasForeignKey("expenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "user")
                        .WithMany("userExpenseShares")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("expense");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Backend.Models.Event", b =>
                {
                    b.Navigation("expenses");

                    b.Navigation("userEvents");
                });

            modelBuilder.Entity("Backend.Models.Expense", b =>
                {
                    b.Navigation("userExpenseShares");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("expenses");

                    b.Navigation("friendships");

                    b.Navigation("recievedFriendRequests");

                    b.Navigation("sentFriendRequests");

                    b.Navigation("spendingGoal")
                        .IsRequired();

                    b.Navigation("userEvents");

                    b.Navigation("userExpenseShares");
                });
#pragma warning restore 612, 618
        }
    }
}
